### ISSUE TITLE
Update Config

### ISSUE THREAD

**Issue by incognitojam** [IncognitoJam/CustomPortals#2]
In its current state, the config is not user friendly. World options should be grouped, and all worlds under a single tree of values.

### Proposed format
```yaml
worlds:
    world:
        material: "1:0" # Stone
        scale: 1.0
    world_nether:
        material: "49:0" # Obsidian
        scale: 8.0
```
