### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by incognitojam** [IncognitoJam/CustomPortals#3]
Add permissions to prevent players from travelling through or constructing portals to specific worlds, unless they have the required permissions.

#### Proposed format
```yaml
permissions:
    customportals.create:
        description: Base permission to allow players to construct portals
        default: true
    customportals.create.[world_name]:
        description: Allows players to construct portals for this world. Must be used in combination with 
.create
    customportals.create.all:
        description: Allows player to create portals for any world, without its specific permission.
    customportals.use:
        description: Base permission to allow players to travel through portals
        default: true
    customportals.use.[world_name]:
        description: Allows players to use portals for this world. Must be used in combination with .use
    customportals.use.all:
        description: Allows player to travel through any portal, without its specific permission.
        default: false
```
